/*
 * This file is generated by jOOQ.
*/
package com.ef.model.jooq;


import com.ef.model.jooq.tables.FlywaySchemaHistory;
import com.ef.model.jooq.tables.RequestHttpLog;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db_parser
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db_parser.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.ef.model.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>db_parser.request_http_log</code>.
     */
    public static final RequestHttpLog REQUEST_HTTP_LOG = com.ef.model.jooq.tables.RequestHttpLog.REQUEST_HTTP_LOG;
}
